# Generated by Django 5.0.7 on 2024-07-22 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=50)),
                ('exchangeShortName', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedTickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta', models.DecimalField(decimal_places=8, max_digits=10)),
                ('volAvg', models.BigIntegerField()),
                ('mktCap', models.BigIntegerField()),
                ('lastDiv', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('range', models.CharField(max_length=50)),
                ('changes', models.DecimalField(decimal_places=8, max_digits=20)),
                ('companyName', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=20)),
                ('cusip', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('ceo', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('fullTimeEmployees', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
                ('dcfDiff', models.DecimalField(decimal_places=8, max_digits=20)),
                ('dcf', models.DecimalField(decimal_places=8, max_digits=20)),
                ('image', models.URLField()),
                ('ipoDate', models.DateField()),
                ('defaultImage', models.BooleanField()),
                ('isEtf', models.BooleanField()),
                ('isActivelyTrading', models.BooleanField()),
                ('isAdr', models.BooleanField()),
                ('isFund', models.BooleanField()),
                ('basic_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_data', to='api.basictickerdata')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('basic_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='api.basictickerdata')),
                ('detailed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='api.detailedtickerdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('adj_close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('unadjusted_volume', models.BigIntegerField()),
                ('change', models.DecimalField(decimal_places=8, max_digits=20)),
                ('change_percent', models.DecimalField(decimal_places=8, max_digits=10)),
                ('vwap', models.DecimalField(decimal_places=8, max_digits=20)),
                ('label', models.CharField(max_length=50)),
                ('change_over_time', models.DecimalField(decimal_places=8, max_digits=20)),
                ('basic_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='api.basictickerdata')),
                ('detailed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='api.detailedtickerdata')),
            ],
        ),
    ]
