# Generated by Django 5.0.7 on 2024-07-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_detailedtickerdata_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedtickerdata',
            name='companyName',
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='changes',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='ipoDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='isActivelyTrading',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='isin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='mktCap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
