# Generated by Django 5.0.7 on 2024-07-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_detailedtickerdata_companyname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='adj_close_price',
            new_name='adjClose',
        ),
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='change_over_time',
            new_name='changeOverTime',
        ),
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='change_percent',
            new_name='changePercent',
        ),
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='close_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='high_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='low_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='open_price',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='historicaltickerdata',
            old_name='unadjusted_volume',
            new_name='unadjustedVolume',
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='changes',
            field=models.DecimalField(decimal_places=8, default=0.3423, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='ipoDate',
            field=models.DateField(default='2020-01-11'),
            preserve_default=False,
        ),
    ]
