# Generated by Django 5.0.7 on 2024-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_adj_close_price_historicaltickerdata_adjclose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='beta',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='mktCap',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='volAvg',
            field=models.BigIntegerField(),
        ),
    ]
