# Generated by Django 5.0.7 on 2024-07-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_detailedtickerdata_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritetickerdata',
            name='detailed_data',
        ),
    ]
