# Generated by Django 5.0.7 on 2024-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_favoritetickerdata_detailed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('publishedAt', models.DateTimeField()),
                ('urlToImage', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
