# Generated by Django 5.0.7 on 2024-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_generalnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnews',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
