# Generated by Django 5.0.7 on 2024-07-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_favoritetickerdata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='basictickerdata',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detailedtickerdata',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generalnews',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
