# Generated by Django 5.0.7 on 2024-07-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_generalnews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalnews',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='generalnews',
            name='urlToImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
