# Generated by Django 5.0.7 on 2024-07-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_detailedtickerdata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnews',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
