# Generated by Django 5.0.7 on 2024-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_generalnews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basictickerdata',
            name='exchange',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basictickerdata',
            name='exchangeShortName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basictickerdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basictickerdata',
            name='symbol',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basictickerdata',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='ceo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='cik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='currency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='cusip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='isin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltickerdata',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
