# Generated by Django 5.0.7 on 2024-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_basictickerdata_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='beta',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='lastDiv',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltickerdata',
            name='changePercent',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
