# Generated by Django 5.0.7 on 2024-07-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_detailedtickerdata_beta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedtickerdata',
            name='ipoDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
