services:
  redis:
    image: redis:7.0.11-alpine
  django:
    container_name: django
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:  # Use `env_file` to properly load environment variables
      - .env
    depends_on:
      - redis