services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend
    command: celery -A backend worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_flower:
    container_name: celery_flower
    build:
      context: ./backend
    command: celery -A backend flower --port=5555 --broker=${CELERY_BROKER}
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "5555:5555"

  celery_beat:
    container_name: celery_beat
    build:
      context: ./backend
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data: